// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClJs-JDOzdczXe9owxRDzZaJOQU65Q7TQ',
    appId: '1:811425695924:web:367e01284c31a32cfe2fe1',
    messagingSenderId: '811425695924',
    projectId: 'mobildovizapp',
    authDomain: 'mobildovizapp.firebaseapp.com',
    storageBucket: 'mobildovizapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRwB1OExknh3INquOWncJJFd83fds1OU',
    appId: '1:811425695924:android:37f14bfafefbde6efe2fe1',
    messagingSenderId: '811425695924',
    projectId: 'mobildovizapp',
    storageBucket: 'mobildovizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBqdM_2CIUh9iH8rPN5KkY46xKnwbANo',
    appId: '1:811425695924:ios:bc2bfe149059ec88fe2fe1',
    messagingSenderId: '811425695924',
    projectId: 'mobildovizapp',
    storageBucket: 'mobildovizapp.appspot.com',
    iosClientId: '811425695924-fiog01sqdc6gd2416bo7f3b287hsv4ut.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobildovizapp',
  );
}
